---
title: "Visualization"
author: "Evan Brociner"
date: "3/15/2022"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)

price.per.hospital.df<- read.csv('/Users/evan.brociner/Desktop/Job_Hunting_Projects/pricing/data/avg_price.csv')
hospital.df<- read.csv('/Users/evan.brociner/Desktop/Job_Hunting_Projects/pricing/data/hospitals_coordinates.csv')
poverrty.rate.df<- read.csv('/Users/evan.brociner/Desktop/Job_Hunting_Projects/pricing/data/poverty_rates.csv')
poverrty.rate.df<- poverrty.rate.df %>% group_by(city,state) %>% slice(1)


price.per.hospital.df<- price.per.hospital.df %>% group_by(npi_number,code,payer) %>% slice(1)

price.per.hospital.df<- merge(x = price.per.hospital.df, y = hospital.df, by = "npi_number", all.x = TRUE)
price.per.hospital.df<- merge(x = price.per.hospital.df, y = poverrty.rate.df, by = c("city",'state'), all.x = TRUE)

price.per.hospital.df<- price.per.hospital.df %>% drop_na()

```


library(ggplot2)
price.per.hospital.df %>% group_by(code) %>%
    cor(km_distance, price) 


```{r}

require(plyr)
corr_km <- function(xx)
{
return(data.frame(COR = cor(xx$km_distance, xx$price)))
}

corr_pov <- function(xx)
{
return(data.frame(COR = cor(xx$poverty.rate, xx$price)))
}

```



```{r}
saves <-ddply(price.per.hospital.df, .(code), corr_km)
saves$observation <- 1:nrow(saves) 

# Change the point size, and shape
ggplot(saves, aes(x=COR, y=observation)) +
  geom_point(size=2, shape=23) +
  scale_x_continuous(limits = c(-1, 1))
```


```{r}
saves <-ddply(price.per.hospital.df, .(code), corr_pov)
saves$observation <- 1:nrow(saves) 
saves
# Change the point size, and shape
ggplot(saves, aes(x=COR, y=observation)) +
  geom_point(size=2, shape=23) +
  scale_x_continuous(limits = c(-1, 1))
```


Whats the variance between prices per code?
```{r}
library(dplyr)

avg.price.df<- read.csv('data/avg_price.csv')


avg.price.df<- avg.price.df %>% group_by(code) %>% summarise(mean=mean(price), sd=sd(price))

```


```{r}
library(ggplot2)
ggplot(avg.price.df, aes(x=code, y=mean)) + 
  geom_point()+
  geom_errorbar(aes(ymin=mean-sd, ymax=mean+sd), width=.2,
                position=position_dodge(0.05))
  

```

Whats the variance between prices per code hospital?
```{r}

price.per.hospital.df %>% group_by(code) %>% summarise(mean=mean(AVG.price.), sd=sd(AVG.price.))

```

What are the significant factors impacting cost?
```{r}

```



Average variability per hopsital location to other hospitals
```{r}

```




Quality = price?
```{r}

```

